### PR TITLE
test: separate out integration tests

### PR DESCRIPTION
**Pull request by nguyentoanit**

### CODE REVIEW

**Comment by moltar** [comment]
Task linked: [GHORG-25 Separate out integration tests](https://app.clickup.com/t/2250003/GHORG-25)

**Review by moltar — CHANGES_REQUESTED** [review]
Need to change GH Actions Workflow to split the tests and run integration test separately.

**Comment by nguyentoanit** [comment]
> Need to change GH Actions Workflow to split the tests and run integration test separately.

Do we need to record integration test's requests? 🤔

**Comment by nguyentoanit** [comment]
> we could also just put `dotenv/config` into jest.config and run jest thru `jest` cli @nguyentoanit

Thanks for your suggestions. I've used `setupFiles` flag to load `dotenv` configs. 👍

**Comment by moltar** [comment]
> > we could also just put `dotenv/config` into jest.config and run jest thru `jest` cli @nguyentoanit
> 
> Thanks for your suggestions. I've used `setupFiles` flag to load `dotenv` configs. 👍

Good idea!!

**Review by moltar — APPROVED** [review]

**Pull request merged**
