### PR TITLE
Chore: generate api clients automatically

### PR DESCRIPTION
**Pull request by nguyentoanit**

### CODE REVIEW

**Comment by moltar** [comment]
Task linked: [GHORG-54 Figure out a solution to generate api clients automatically](https://app.clickup.com/t/2250003/GHORG-54)

**Comment by nguyentoanit** [comment]
@moltar:
I think it will be better if we generate API client filename and class name base on [model directory](https://github.com/ScaleLeap/selling-partner-api-sdk/pull/69/files#diff-1c4640b58e919387f98c888c580bc625d52db1f48a20ae42f00f7a6ceba50094R12)?
It also prevents API clients from duplication.

What do you think?

**Comment by moltar** [comment]
> @moltar:
> I think it will be better if we generate API client filename and class name base on [model directory](https://github.com/ScaleLeap/selling-partner-api-sdk/pull/69/files#diff-1c4640b58e919387f98c888c580bc625d52db1f48a20ae42f00f7a6ceba50094R12)?
> It also prevents API clients from duplication.
> 
> What do you think?

Fine by me

**Comment by nguyentoanit** [comment]
@moltar: 
I implemented a script to generate API clients.
Please help me review this PR. Thanks.

**Review by moltar — APPROVED** [review]

**Pull request merged**
