### PR TITLE
chore: exclude enum mapper in model generator

### PR DESCRIPTION
**Pull request by nguyentoanit**
At the moment, we are appending union string into types which are enums. 
`ItemApprovalType[]` -> `(ItemApprovalType | "LEONARDI_APPROVAL")[]`

This will help us stop them because of [the problems with enums in TS.](https://dev.to/dvddpl/whats-the-problem-with-typescript-enums-2okj)

However, API models were requiring an enum array as a parameter recently (Maybe an enum later).
This caused [a compatible problem in compilation.
](https://github.com/ScaleLeap/selling-partner-api-sdk/actions/runs/4910422051/jobs/8767574140)

Should we exclude this step in model generator?

@moltar : What do you think?
Or any idea to solve them?

### CODE REVIEW

**Comment by nguyentoanit** [comment]
@moltar : Please have a look in this if you have time. Thanks.

**Comment by nguyentoanit** [comment]
@moltar : Perhaps, you forgot this PR 👆 . 😄

**Comment by nguyentoanit** [comment]
> I think these kinds of drastic changes are hard as it would be a massive breaking change, no?

Yeah. I agree with you. That would be a massive breaking change.
However, After generating clients from models, they are requiring an enum array in some places, not a union string.
See [these logs](https://github.com/ScaleLeap/selling-partner-api-sdk/actions/runs/4910422051/jobs/8767574140).

Therefore, There will be a [a compatible problem in compilation.](https://github.com/ScaleLeap/selling-partner-api-sdk/actions/runs/4910422051/jobs/8767574140). Because we are "mapping" [enums to union string](https://github.com/ScaleLeap/selling-partner-api-sdk/pull/696/files#diff-ba48db8f257b58c9b15436ddd7e5a402ae823cc9b5d5dbfa237903d8ed037b0bL54).
And this are blocking our generator.

**Comment by moltar** [comment]
I think the correct type should be:


```ts
ItemApprovalType[] | EnumType[] | undefined
```

And not

```ts
(ItemApprovalType | EnumType)[] | undefined
```

The second suggests that the array can be of mixed type, which I think, _is_ wrong.

**Comment by nguyentoanit** [comment]
Looks like, there was an update in models or OpenAPI generator which fixed this issue.
Close this one because [our actions](https://github.com/ScaleLeap/selling-partner-api-sdk/actions/workflows/generate-models.yml) were recovered.

**Pull request closed without merging**
