### PR TITLE
fix: re-generate missing method in API clients

### PR DESCRIPTION
**Pull request by nguyentoanit**
- Re-generate model when apply changes in https://github.com/ScaleLeap/selling-partner-api-sdk/pull/203

### CODE REVIEW

**Comment by moltar** [comment]
Probably should go together with #203 that way we trigger one release only.

**Comment by nguyentoanit** [comment]
> Probably should go together with #203 that way we trigger one release only.

Sure. I splitted up for better review.

**Comment by moltar** [comment]
> > Probably should go together with #203 that way we trigger one release only.
> 
> Sure. I splitted up for better review.

Yup good idea :)

**Comment by moltar** [comment]
Task linked: [GHORG-71 Fix: missing methods in API models](https://app.clickup.com/t/2250003/GHORG-71)

**Pull request merged**
