### PR TITLE
Chore: only generate latest api version

### PR DESCRIPTION
**Pull request by nguyentoanit**

### CODE REVIEW

**Comment by moltar** [comment]
Task linked: [GHORG-51 Only generate latest API model version](https://app.clickup.com/t/2250003/GHORG-51)

**Comment by moltar** [comment]
It is unclear what this is trying to do?

**Comment by nguyentoanit** [comment]
> It is unclear what this is trying to do?

@moltar:

API model published a new version. But still keep previous version.
Such as: [catalog-items-api-model](https://github.com/amzn/selling-partner-api-models/tree/main/models/catalog-items-api-model)
There are two versions in an API model directory:
- v0
- 2020-12-01

Therefore, I think we only need to keep latest version. That is enough?

**Comment by nguyentoanit** [comment]
Merged in https://github.com/ScaleLeap/selling-partner-api-sdk/pull/67

**Pull request closed without merging**
